<a href="https://colab.research.google.com/github/ChristianJovenGarcia/BME3053C-Spring-2025/blob/main/study-guides/midterm-study-guide_02_21_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BME3053C Midterm Study Guide

This Jupyter Notebook provides practice problems covering concepts included in the midterm.

- Type conversion
- Conditionals (if/elif/else)
- Boolean logic
- Loops (for/while)
- List slicing
- Variable scope
- References and mutability
- NumPy array operations (basic arithmetic, broadcasting)
- Matplotlib basics (plotting)


Try each code snippet, predict the output, and then run the code to confirm your understanding.

### Original Lesson Link: [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/uf-bme/BME3053C-Spring-2025/blob/main/study-guides/midterm-study-guide.ipynb)




## Tips to Succeed

- Don't rush through the problems! Pay close attention to the syntax in each code cell (especially in print statements).
- Try tweaking the code cells in this notebook to see how changes affect the output. Write down your predictions and the modified code on paper before running it.
- Review the output and compare it with your predictions to reinforce your understanding.


## Conditionals and Boolean Logic

- Conditionals allow you to execute different blocks of code based on certain conditions.
- Boolean logic helps in combining multiple conditions using logical operators like `and`, `or`, and `not`.

**Task:** Predict the output of the code below.


In [1]:
x = 6
y = 3

if x > 5 and y < 3:
    print("Case 1")
elif x == 6 or y == 3:
    print("Case 2")
else:
    print("Case 3")
print("Done")

Case 2
Done


Prediction:
Case 2
Done


## Multiple Conditionals in a Single Statement

* You can combine multiple conditions in a single `if`, `elif`, or `else` statement using logical operators like `and`, `or`, and `not`.
* When using `and`, the condition will only be true if both conditions are true.
* When using `or`, the condition will be true if at least one of the conditions is true.
* Parentheses will help ensure the condition is evaluated in the order you want.

### Practice

Predict the prints, then run the cell below to check.




In [2]:
a = 10
b = 9
c = 7

if (a > b) and (b < c): #9 < 7, no
    print("Condition 1")
elif (a > b) or (b < c): #1st part happens
    print("Condition 2")
else:
    print("Condition 3")
print("Done")

Condition 2
Done


Prediction:
Condition 3
Done
#INCORRECT
you're a dumbass
it says or, not and

## Type Conversion

- Type conversion is the process of converting one data type to another.
- This is useful when you need to convert data from one type to another.
- The `int()`, `str()`, and `float()` functions are commonly used for type conversion.


**On the test, you could just write int or float. You wouldn't need to write <class 'int'> or  <class 'float'>**

 **Task:** Understand how to convert between different data types using `int()`, `str()`, and `float()` functions.



Prediction:
123 integer
12 int
True string
good job

In [ ]:
num_str = "123"
num_int = int(num_str)
print(num_int, type(num_int))

float_num = 12.34
int_num = int(float_num)
print(int_num, type(int_num))

bool_val = True
str_bool = str(bool_val)
print(str_bool, type(str_bool))


123 <class 'int'>
12 <class 'int'>
True <class 'str'>


## For Loops

- A for loop is used to iterate over a sequence (such as a list, tuple, dictionary, set, or string).
- The range() function is commonly used with for loops to generate a sequence of numbers.


### Prompt

```python
total_sum = 0
for i in range(3, 8):  # 3, 4, 5, 6, 7
    total_sum += i
print(total_sum)
```

**Task:** Predict the final value of `total_sum`.


In [3]:
total_sum = 0
for i in range(3, 6):
    total_sum += i
    print('i=',i,'total_sum=',total_sum)

print(total_sum)

i= 3 total_sum= 3
i= 4 total_sum= 7
i= 5 total_sum= 12
12


Prediction:
i=3 i=4 i=5 i=6
18
#INCORRECT
The ends of ranges in PYTHON are non-inclusive
this means we go from 3 to 5

## While Loops

- A while loop is used to execute a block of code repeatedly as long as a condition is true.
- The condition is evaluated before each iteration of the loop.

**Task:** Observe how the loop increments `count` and prints when `count == 2`.




In [4]:
count = 0
count2=0

while count < 5:#
    count2+=1#IIIII
    if count == 2:
        print("Halfway there!","count2=",count2)
    count += 1#IIIII

print("Final count:", count)
print("Final count2:",count2)

Halfway there! count2= 3
Final count: 5
Final count2: 5


Prediction:
Halfway there! count2=3
Final: 5
Final2: 5

## List Slicing

- List slicing allows you to extract a portion of a list.
- The syntax is `list[start:stop:step]`.
- The start index is inclusive, the stop index is exclusive, and the step is optional.
- Negative indices can be used to slice from the end of the list.
- The step can be negative to reverse the order of the slice.



In [5]:
nums = [10, 20, 30, 40, 50, 60]
print("nums[2:] =>", nums[2:])
print("nums[:3] =>", nums[:3])
print("nums[1:5:2] =>", nums[1:5:2])
print("nums[1:4] =>", nums[1:4])
print("nums[-3:-1:1] =>", nums[-3:-1:1])#Starts at -3, which is 40, right before it hits -1, 60. Iterates to the right (+1)
print("nums[-3:1:-1] =>", nums[-3:1:-1])#Starts at -3, which is 40, right before it hits 1, 20. Iterates to the left (-1)

nums[2:] => [30, 40, 50, 60]
nums[:3] => [10, 20, 30]
nums[1:5:2] => [20, 40]
nums[1:4] => [20, 30, 40]
nums[-3:-1:1] => [40, 50]
nums[-3:1:-1] => [40, 30]


[30, 40, 50, 60],

[40, 50, 60],

[20, 40],

[20, 30, 40],

[40, 30]

[40, 50]
#INCORRECT
misread [:3] as [3:]

nums[-3:-1:1] => [40, 50]

nums[-3:1:-1] => [40, 30]



## Variable Scope

Variable scope refers to the context in which a variable is defined and accessible. In Python, there are two main types of variable scope:

1. **Global Scope**: Variables defined outside of any function or block, accessible throughout the entire script.
2. **Local Scope**: Variables defined within a function or block, accessible only within that function or block.

Understanding variable scope is crucial for avoiding naming conflicts and ensuring that variables are used correctly within their intended context.


**Task:** Notice how `my_var` inside the function is not the same as the **global** `my_var`.


In [6]:
my_var = 100
def multiply_by_two(x):
    my_var = x * 2
    return my_var

result = multiply_by_two(5)
print("my_var =", my_var)
print("result =", result)

my_var = 100
result = 10


Prediction:

my_var = 100

result = 10

## Function Parameters and Return Values

- When working with functions, it's important to understand how return values and variable scope work.
- In the example below, the function `add_two_numbers` is supposed to return the sum of two numbers, but it currently returns x.


**Task:** Evaluate the importance of return values in the function `add_two_numbers`.


In [7]:
var1 = 7
def add_two_numbers(x,y):#lmao you function is broekn
    local_var = x + y
    return x

var2 =  add_two_numbers(5,6)#returned 5
var3 = var1+var2#12
print(var3)


12


Prediction:

12

## References & Mutability

- Lists are mutable, meaning their contents can be changed after they are created.
- When a list is assigned to a new variable, the new variable references the same list.

**Task:** Understand how inserting into `another_ref` also affects `a_list` because both point to the same list.


In [15]:
a_list = [5, 6]
another_ref = a_list
another_ref.append(10)#adds 10 to both a_list and another_ref
#remember that with references like this, python equates the two as the same
#say we want a list copy that doesn't influence the old one, we do
og_list = [5, 6]
correct_list = og_list.copy()#we must use .copy()
correct_list.append(10)

print("a_list =", a_list)
print("another_ref =", another_ref)
print('and now what we wanted to see...')

#these were added after the fact
print(og_list)
print(correct_list)

a_list = [5, 6, 10]
another_ref = [5, 6, 10]
and now what we wanted to see...
[5, 6]
[5, 6, 10]


Prediction:

[5, 6, 10]

[5, 6, 10]

## NumPy: Basic Arithmetic & Broadcasting

- NumPy is a powerful library for numerical computing in Python.
- It provides a fast and efficient way to handle large arrays and matrices of numerical data.
- Broadcasting is a feature of NumPy that allows for element-wise operations between arrays of different shapes.


**Task:** Practice element-wise operations.\*\*




Prediction:

[5, 7, 9]

[4, 8, 12]

[3, 5, 7]

nothing lol they didn't put an output on this print

[idk

#INCORRECT
cuz u put idk lol

z_matrix + x_arr =>
[[ 3  6  9]
 [ 6  9 12]]

In [19]:
import numpy as np
x_arr = np.array([2, 4, 6])
y_arr = np.array([1, 1, 1])
z_matrix = np.array([[1, 2, 3], [4, 5, 6]])

print("x_arr + 3 =>", x_arr + 3)
print("x_arr * 2 =>", x_arr * 2)
print("x_arr + y_arr =>", x_arr + y_arr)
print("z_matrix + x_arr =>")
print(z_matrix + x_arr)
print(x_arr * z_matrix)

x_arr + 3 => [5 7 9]
x_arr * 2 => [ 4  8 12]
x_arr + y_arr => [3 5 7]
z_matrix + x_arr =>
[[ 3  6  9]
 [ 6  9 12]]
[[ 2  8 18]
 [ 8 20 36]]


## Matplotlib Basics

- Matplotlib is a popular library for creating static, animated, and interactive visualizations in Python.
- It provides a MATLAB-like interface for creating plots and graphs.  
- importing matplotlib is commonly done with the alias `plt`.
- `plt.plot()` is used to create a line plot.
- `plt.scatter()` is used to create a scatter plot.
- `plt.bar()` is used to create a bar plot.
- `plt.hist()` is used to create a histogram.
- `plt.title()` is used to set the title of the plot.
- `plt.xlabel()` is used to set the label of the x-axis.
- `plt.ylabel()` is used to set the label of the y-axis.
- `plt.grid()` is used to show a grid on the plot.
- `plt.legend()` is used to show a legend on the plot.

```python
import matplotlib.pyplot as plt
```

**Task:** Understand how to create a basic line plot with labeled axes and a grid.\*\*


In [ ]:
import matplotlib.pyplot as plt

plt.plot([0, 1, 2], [0, 1, 4], 'bo-', label='Quadratic Growth')
plt.scatter([0, 1, 2], [1, 2, 3], color='red', label='Data Points')
plt.title("Quadratic Growth with Scatter Plot")
plt.xlabel("X")
plt.ylabel("Y")
plt.grid(True)
plt.legend()
plt.show()

## **Good luck!**
